### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by XClaws** [TravisWheelerLab/NINJA#35]
Dear Team,

I encountered this error when building the NINJA:
g++-7 -std=gnu++11 -Wall -mssse3 -fopenmp -O3   -c -o NINJA/Stack.o NINJA/Stack.cpp
make: g++-7: Command not found
<builtin>: recipe for target 'NINJA/Stack.o' failed
make: *** [NINJA/Stack.o] Error 127

Could you please help me to solve this problem?
Thank you!

**Comment by glesica** [comment]
Looks like it can’t find GCC 7, which OS (and distro if you’re on Linux) and version are you on?

**Comment by traviswheeler** [comment]
For what it's worth:  this very explicit "g++-7" requirement is a short-lived thing (because ninja currently doesn't build on newer versions). We're working right now on compatibility with newer compilers, so that we can go back to a more general "g++"

**Comment by XClaws** [comment]
> 
> 
> Looks like it can’t find GCC 7, which OS (and distro if you’re on Linux) and version are you on?

Dear Glesica,

This is the version info:
Linux 4.4.0-184-generic x86_64

thank you for the help.

**Comment by XClaws** [comment]
> 
> 
> Looks like it can’t find GCC 7, which OS (and distro if you’re on Linux) and version are you on?



> 
> 
> For what it's worth: this very explicit "g++-7" requirement is a short-lived thing (because ninja currently doesn't build on newer versions). We're working right now on compatibility with newer compilers, so that we can go back to a more general "g++"

Dear colleague,

Thank you for replying. If I understand correctly, this error has to do with the compiler of my current OS system.
That means it can not be fixed if I don't change the OS version.
Thank you for help. I look forward to hearing from you.

**Comment by traviswheeler** [comment]
This is a matter of ensuring that you have a particular version of gcc installed on your OS.  Since you have Linux 4.4, I'm sure it supports gcc 7.  

(1) You'll need to determine which distribution (e.g. Ubuntu, or Redhat) you're using.  You might try 'cat /etc/*release' 
 (or others, see: https://whatsmyos.com/#:~:text=what%20distribution)
(2) You'll need to follow standard instructions for installing gcc7 on your particular distribution.  Google can help.

Beyond this - we can't provide tech support for your system setup. If the hints I've given above aren't enough to help you on your way, I suggest reaching out to someone local who can provide tech support.

**Comment by XClaws** [comment]
> 
> 
> This is a matter of ensuring that you have a particular version of gcc installed on your OS. Since you have Linux 4.4, I'm sure it supports gcc 7.
> 
> (1) You'll need to determine which distribution (e.g. Ubuntu, or Redhat) you're using. You might try 'cat /etc/*release'
> (or others, see: https://whatsmyos.com/#:~:text=what%20distribution)
> (2) You'll need to follow standard instructions for installing gcc7 on your particular distribution. Google can help.
> 
> Beyond this - we can't provide tech support for your system setup. If the hints I've given above aren't enough to help you on your way, I suggest reaching out to someone local who can provide tech support.

Thank you very much for the explanation!
It is clear to me now.
